import type {Metadata} from "next";
import "./globals.css";
import {Inter as FontSans} from "next/font/google"
import {cn} from "@/lib/utils"
import {ToastContainer} from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import {CustomSessionProvider} from "@/components/ui/CustomSessionProvider";
import {Toolbar} from "@/components/ui/Toolbar";
import Particles from "@/components/background/particles";
import AnimatedGridPattern from "@/components/background/animated-grid-pattern";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by editor next app",
};

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
})

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <CustomSessionProvider>
            <html lang="en">
            <body
                className={cn(
                    "min-h-screen bg-background font-sans antialiased dark flex flex-col",
                    fontSans.variable
                )}
            >
            <Particles className={"absolute h-screen w-screen z-0"} quantity={200} />
            <div className={"relative z-10 flex flex-col h-full min-h-screen"}>
                <Toolbar/>
                {children}
                <ToastContainer position={"bottom-right"} stacked theme={"dark"}/>
            </div>
            </body>
            </html>
        </CustomSessionProvider>
    );
}
