import type {Metadata} from "next";
import "./globals.css";
import {Inter as FontSans} from "next/font/google"
import {cn} from "@/lib/utils"
import {ToastContainer} from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import {CustomSessionProvider} from "@/components/ui/CustomSessionProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
})

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={cn(
                "min-h-screen bg-background font-sans antialiased dark",
                fontSans.variable
            )}
        >
        <CustomSessionProvider>
            {children}
            <ToastContainer position={"bottom-right"} stacked theme={"dark"}/>
        </CustomSessionProvider>
        </body>
        </html>
    );
}
